### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '404: Not Found'

### ISSUE THREAD

**Issue by Aakarshan-chauhan** [dkalpakchi/quinductor#2]
`qi.download('en')
tools = qi.use('en')`

gives the value error as mentioned in the title.
On further inspection, the error comes from the file

> /root/quinductor_resources/en/pos_ngrams/ewt_train_freq
> /root/quinductor_resources/en/pos_ngrams/ewt_dev_freq

On printing the contents of the files, 
> ['404: Not Found']

Full Traceback
![image](https://user-images.githubusercontent.com/54583758/161417301-3e4df19a-7ff2-4326-a647-b1c2ee51f92c.png)

**Comment by HarshitSati** [comment]
facing the same issue^^

**Comment by dkalpakchi** [comment]
Hi! 

Thank you very much for your detailed bug report! I believe I have fixed the bug in the newly baked 0.2.0 release of quinductor. I've also added some new functionality making it easier for you guys to test the package (see README and changelog in the Github releases).

All the best,
Dmytro

**Comment by HarshitSati** [comment]
Thank you so much for this! The code works now, if we run into more troubles we'll contact you!
